// AGENTS.md emitter — generates structured context for AI coding agents
// Output: AGENTS.md committed to the repository root for agents to load
import type { ArchitectureArtifact } from './artifact.ts';
import type { ArtifactInvariantRule } from './artifact.ts';

function ruleDescription(rule: ArtifactInvariantRule): string {
  if (rule.kind === 'DenyFlow') {
    return `**FORBIDDEN**: \`${rule.from}\` must NOT directly access \`${rule.to}\``;
  }
  if (rule.kind === 'DenyDataFlow') {
    return `**FORBIDDEN**: data \`${rule.data}\` must NOT flow to \`${rule.to}\``;
  }
  if (rule.kind === 'RequireEncryption') {
    return `**REQUIRED**: All flows from \`${rule.from}\` to \`${rule.to}\` must be encrypted`;
  }
  return `${(rule as { kind: string }).kind}: ${JSON.stringify(rule)}`;
}

export function emitAgentsMarkdown(artifact: ArchitectureArtifact): string {
  const lines: string[] = [];

  lines.push(`# Architecture Ground Rules (AGENTS.md)`);
  lines.push(`<!-- Auto-generated by aglc emit-context. Do not edit manually. -->`);
  lines.push(`<!-- Source: ${artifact.sourcePath} -->`);
  lines.push('');
  lines.push(`> This file is machine-verified truth. Rules below are enforced by aglang's commit-time gates`);
  lines.push(`> (Z3-backed architecture checks plus direct policy evaluators). Violations block the commit with an exact explanation.`);
  lines.push(`> **When in doubt, consult this file before writing code.**`);
  lines.push('');

  if ((artifact.enforcement ?? []).length > 0) {
    lines.push(`## Enforcement Semantics`);
    lines.push('');
    lines.push(`| Declaration | Level | Mechanism |`);
    lines.push(`|-------------|-------|-----------|`);
    for (const item of artifact.enforcement) {
      lines.push(`| \`${item.declaration}\` | \`${item.level}\` | ${item.mechanism} |`);
    }
    lines.push('');
  }

  // Infrastructure nodes
  if ((artifact.nodes ?? []).length > 0) {
    lines.push(`## Infrastructure Nodes`);
    lines.push('');
    lines.push(`| Name | Type | Trust | Protocol | Auth |`);
    lines.push(`|------|------|-------|----------|------|`);
    for (const n of artifact.nodes) {
      lines.push(`| \`${n.name}\` | \`${n.type}\` | ${n.trust ?? '—'} | ${n.protocol ?? '—'} | ${n.auth ?? '—'} |`);
    }
    lines.push('');
  }

  if ((artifact.resources ?? []).length > 0) {
    lines.push(`## Architecture Resources`);
    lines.push('');
    lines.push(`| Name | Type | Trust | Protocol | Auth |`);
    lines.push(`|------|------|-------|----------|------|`);
    for (const r of artifact.resources) {
      lines.push(`| \`${r.name}\` | \`${r.type}\` | ${r.trust ?? '—'} | ${r.protocol ?? '—'} | ${r.auth ?? '—'} |`);
    }
    lines.push('');
  }

  // Component → file mapping
  const componentNames = Object.keys(artifact.mappings);
  if (componentNames.length > 0) {
    lines.push(`## Code Components`);
    lines.push('');
    lines.push(`These logical components map your code files to the architecture nodes above.`);
    lines.push('');
    for (const comp of componentNames) {
      const meta = (artifact.componentMeta ?? []).find(m => m.component === comp);
      lines.push(`### \`${comp}\``);
      lines.push(`- **File glob**: \`${artifact.mappings[comp]}\``);
      if (meta?.role) lines.push(`- **Role**: \`${meta.role}\``);
      if (meta?.layer) lines.push(`- **Layer**: \`${meta.layer}\``);
      const relatedRules = artifact.invariants.flatMap(inv =>
        inv.rules
          .filter(r => r.kind === 'DenyDataFlow' ? r.to === comp : r.from === comp || r.to === comp)
          .map(r => ({ invName: inv.name, rule: r }))
      );
      if (relatedRules.length > 0) {
        lines.push(`- **Rules affecting this component:**`);
        for (const { invName, rule } of relatedRules) {
          lines.push(`  - [${invName}] ${ruleDescription(rule)}`);
        }
      }
      lines.push('');
    }
  }

  // Invariants (architectural laws)
  if (artifact.invariants.length > 0) {
    lines.push(`## Architectural Invariants`);
    lines.push('');
    lines.push(`These are universal laws — they apply to ALL code, not just tests.`);
    lines.push('');
    for (const inv of artifact.invariants) {
      lines.push(`### \`${inv.name}\``);
      for (const rule of inv.rules) {
        lines.push(`- ${ruleDescription(rule)}`);
      }
      lines.push('');
    }
  }

  // Enum types (domain vocabulary)
  if ((artifact.enums ?? []).length > 0) {
    lines.push(`## Domain Enums`);
    lines.push('');
    lines.push(`Use these exact values in your code. The solver knows about them.`);
    lines.push('');
    for (const e of artifact.enums) {
      lines.push(`### \`${e.name}\``);
      lines.push(`Values: ${e.values.map(v => `\`${v}\``).join(' | ')}`);
      lines.push('');
    }
  }

  // Data contracts
  if ((artifact.dataTypes ?? []).length > 0) {
    lines.push(`## Data Contracts`);
    lines.push('');
    lines.push(`These are the canonical data shapes for this system.`);
    lines.push('');
    for (const d of artifact.dataTypes) {
      lines.push(`### \`${d.name}\``);
      lines.push('');
      lines.push(`| Field | Type |`);
      lines.push(`|-------|------|`);
      for (const f of d.fields) {
        lines.push(`| \`${f.key}\` | \`${f.typeExpr}\` |`);
      }
      lines.push('');
    }
  }

  // State machine transitions (advisory — not Z3-enforced, but agents MUST follow these)
  if ((artifact.stateMachines ?? []).length > 0) {
    lines.push(`## State Machine Rules`);
    lines.push('');
    lines.push(`> ⚠️ **Advisory rules** — not yet Z3-enforced at commit time, but you MUST follow these.`);
    lines.push(`> Agents: do NOT write code that performs transitions not listed as \`allow\` here.`);
    lines.push('');
    for (const sm of artifact.stateMachines) {
      lines.push(`### \`${sm.name}\` — \`${sm.onType}.${sm.onField}\``);
      lines.push('');
      const allows = sm.transitions.filter(t => t.kind === 'allow');
      const denies = sm.transitions.filter(t => t.kind === 'deny');
      if (allows.length > 0) {
        lines.push(`**Allowed transitions:**`);
        for (const t of allows) {
          lines.push(`- \`${t.from}\` → \`${t.to}\``);
        }
      }
      if (denies.length > 0) {
        lines.push('');
        lines.push(`**Explicitly forbidden transitions:**`);
        for (const t of denies) {
          lines.push(`- ~~\`${t.from}\` → \`${t.to}\`~~ ❌`);
        }
      }
      lines.push('');
    }
  }

  // Permission rules (advisory — not Z3-enforced yet)
  if ((artifact.permissions ?? []).length > 0) {
    lines.push(`## Permission Rules`);
    lines.push('');
    lines.push(`> ⚠️ **Advisory rules** — not yet Z3-enforced at commit time, but you MUST follow these.`);
    lines.push(`> Agents: implement all access control checks according to these rules.`);
    lines.push('');
    for (const perm of artifact.permissions) {
      lines.push(`### \`${perm.name}\` — on \`${perm.onType}\``);
      lines.push('');
      lines.push(`| Role | Operations | Condition | Effect |`);
      lines.push(`|------|------------|-----------|--------|`);
      for (const rule of perm.rules) {
        const role = rule.roleEnum === '*' ? '`*` (any)' : `\`${rule.roleEnum}.${rule.roleValue}\``;
        const ops = rule.operations.map(o => `\`${o}\``).join(', ');
        const cond = rule.whenField ? `when \`${rule.whenField}\`` : '—';
        const effect = rule.kind === 'allow' ? '✅ allow' : '❌ deny';
        lines.push(`| ${role} | ${ops} | ${cond} | ${effect} |`);
      }
      lines.push('');
    }
  }

  // API Contracts (route-level enforcement)
  if ((artifact.contracts ?? []).length > 0) {
    lines.push(`## API Contracts`);
    lines.push('');
    lines.push(`> 🔒 **Enforced at commit time** — route additions/renames in \`implements\` components`);
    lines.push(`> and undeclared fetch() calls in \`consumes\` components will block the commit.`);
    lines.push('');

    // Show which components implement/consume each contract
    const contractImpls = new Map<string, string[]>();
    const contractConsumers = new Map<string, string[]>();
    for (const cc of artifact.componentContracts ?? []) {
      for (const contractName of cc.implements ?? []) {
        if (!contractImpls.has(contractName)) contractImpls.set(contractName, []);
        contractImpls.get(contractName)!.push(cc.component);
      }
      for (const contractName of cc.consumes ?? []) {
        if (!contractConsumers.has(contractName)) contractConsumers.set(contractName, []);
        contractConsumers.get(contractName)!.push(cc.component);
      }
    }

    for (const contract of artifact.contracts) {
      lines.push(`### \`${contract.name}\``);
      lines.push('');
      const impls = contractImpls.get(contract.name) ?? [];
      const consumers = contractConsumers.get(contract.name) ?? [];
      if (impls.length > 0) {
        lines.push(`- **Implemented by**: ${impls.map(c => `\`${c}\``).join(', ')}`);
      }
      if (consumers.length > 0) {
        lines.push(`- **Consumed by**: ${consumers.map(c => `\`${c}\``).join(', ')}`);
      }
      lines.push('');
      lines.push(`| Method | Route | Return Type |`);
      lines.push(`|--------|-------|-------------|`);
      for (const ep of contract.endpoints) {
        if (ep.kind === 'http') {
          lines.push(`| \`${ep.method}\` | \`${ep.path}\` | \`${ep.returnType ?? '—'}\` |`);
        } else if (ep.kind === 'graphql') {
          const args = ep.inputTypes?.length ? `(${ep.inputTypes.join(', ')})` : '';
          lines.push(`| \`${ep.operation}\` | \`${ep.operationName}${args}\` | \`${ep.returnType ?? '—'}\` |`);
        } else if (ep.kind === 'grpc') {
          lines.push(`| \`rpc\` | \`${ep.rpcName}(${ep.inputMessage}) → ${ep.outputMessage}\` | — |`);
        } else if (ep.kind === 'queue_publish') {
          lines.push(`| publishes | \`${ep.topic}\` | — |`);
        } else if (ep.kind === 'queue_subscribe') {
          lines.push(`| subscribes | \`${ep.topic}\` | — |`);
        }
      }
      lines.push('');
    }
  }

  if ((artifact.workflowPolicies ?? []).length > 0) {
    lines.push(`## Workflow Policies`);
    lines.push('');
    lines.push(`> **Enforced at commit time** — GitHub Actions publish, deploy, release, permission, and step-order rules are checked by the workflow policy gate.`);
    lines.push('');
    for (const policy of artifact.workflowPolicies) {
      lines.push(`### \`${policy.name}\``);
      for (const rule of policy.rules) {
        if (rule.kind === 'ActionRule') {
          const when = rule.when
            ? rule.when.kind === 'pull_request' ? ' when pull_request' : ` when ${rule.when.kind} "${rule.when.value}"`
            : '';
          lines.push(`- **${rule.effect.toUpperCase()}** \`${rule.action}\` from \`${rule.workflow}\` to \`${rule.target}\`${when}`);
        } else if (rule.kind === 'PermissionRule') {
          const when = rule.when
            ? rule.when.kind === 'pull_request' ? ' when pull_request' : ` when ${rule.when.kind} "${rule.when.value}"`
            : '';
          lines.push(`- **${rule.effect.toUpperCase()}** permission \`${rule.workflow}\` \`${rule.permission}: ${rule.access}\`${when}`);
        } else {
          lines.push(`- **REQUIRE BEFORE** \`${rule.workflow}\`: \`${rule.before}\` → \`${rule.after}\``);
        }
      }
      lines.push('');
    }
  }

  if ((artifact.changePolicies ?? []).length > 0) {
    lines.push(`## Change Policies`);
    lines.push('');
    lines.push(`> **Enforced at commit time** — related components must be changed together in the same checked diff.`);
    lines.push(`> Agents: when these rules fire, update the required component instead of bypassing the policy.`);
    lines.push('');
    for (const policy of artifact.changePolicies) {
      lines.push(`### \`${policy.name}\``);
      for (const rule of policy.rules) {
        lines.push(`- **REQUIRE TOUCHED** \`${rule.required}\` when \`${rule.trigger}\` changes`);
      }
      lines.push('');
    }
  }

  lines.push(`---`);
  lines.push(`*Generated by [aglc](https://github.com/your-org/aglang) — Architecture Ground Language Compiler*`);

  return lines.join('\n');
}
