// Converts an OpenAPI 3.x JSON spec to aglang contract declarations.
// Groups endpoints by first tag (fallback: first path segment, fallback: 'Default').
// Also generates data blocks from top-level component schemas (scalar types only).

export interface OpenApiImportResult {
  ag: string;
  contracts: number;
  endpoints: number;
  dataTypes: number;
}

function firstPathSegment(path: string): string {
  const parts = path.split('/').filter(p => p && !p.startsWith('{'));
  return parts[0] ?? 'Default';
}

function toPascalCase(s: string): string {
  return s.replace(/[-_/\s]+(.)/g, (_, c: string) => c.toUpperCase())
          .replace(/^(.)/, (_: string, c: string) => c.toUpperCase());
}

function extractReturnType(operation: Record<string, unknown>): string | undefined {
  const responses = operation.responses as Record<string, unknown> | undefined;
  if (!responses) return undefined;
  const ok = (responses['200'] ?? responses['201']) as Record<string, unknown> | undefined;
  if (!ok) return undefined;
  const content = ok.content as Record<string, unknown> | undefined;
  if (!content) return undefined;
  const json = (content['application/json'] ?? content['*/*']) as Record<string, unknown> | undefined;
  if (!json) return undefined;
  const schema = json.schema as Record<string, unknown> | undefined;
  if (!schema) return undefined;
  if (schema.type === 'array') {
    const items = schema.items as Record<string, unknown> | undefined;
    const ref = items?.['$ref'] as string | undefined;
    if (ref) return toPascalCase(ref.split('/').pop()!) + '[]';
    return 'object[]';
  }
  if (schema['$ref']) {
    return toPascalCase((schema['$ref'] as string).split('/').pop()!);
  }
  if (schema.type === 'string') return 'string';
  if (schema.type === 'integer' || schema.type === 'number') return 'number';
  if (schema.type === 'boolean') return 'boolean';
  return undefined;
}

function mapSchemaFieldType(schema: Record<string, unknown>): string {
  if (schema['$ref']) {
    return toPascalCase((schema['$ref'] as string).split('/').pop()!);
  }
  if (schema.type === 'array') {
    const items = schema.items as Record<string, unknown> | undefined;
    const inner = items ? mapSchemaFieldType(items) : 'object';
    return `${inner}[]`;
  }
  if (schema.type === 'string') return 'string';
  if (schema.type === 'integer' || schema.type === 'number') return 'number';
  if (schema.type === 'boolean') return 'boolean';
  if (schema.type === 'object') return 'object';
  return 'unknown';
}

export function importOpenApi(specJson: string): OpenApiImportResult {
  const spec = JSON.parse(specJson) as Record<string, unknown>;
  const paths = (spec.paths ?? {}) as Record<string, Record<string, unknown>>;
  const HTTP_METHODS = ['get', 'post', 'put', 'delete', 'patch', 'head', 'options'];
  const groups = new Map<string, string[]>();

  let endpointCount = 0;

  for (const [path, pathItem] of Object.entries(paths)) {
    for (const method of HTTP_METHODS) {
      const operation = pathItem[method] as Record<string, unknown> | undefined;
      if (!operation) continue;

      const tags = operation.tags as string[] | undefined;
      const group = tags?.[0] ? toPascalCase(tags[0]) : toPascalCase(firstPathSegment(path));
      const contractName = group || 'Default';

      if (!groups.has(contractName)) groups.set(contractName, []);

      const returnType = extractReturnType(operation);
      const line = `  ${method.toUpperCase()} "${path}"${returnType ? ` -> ${returnType}` : ''}`;
      groups.get(contractName)!.push(line);
      endpointCount++;
    }
  }

  const lines: string[] = [
    `// Generated by aglc import-openapi`,
    `// Source: OpenAPI ${(spec.openapi ?? spec.swagger ?? '?')} spec`,
    `// Title: ${(spec.info as Record<string, unknown>)?.title ?? 'Unknown'}`,
    ``,
  ];

  for (const [name, endpoints] of groups) {
    lines.push(`contract ${name} {`);
    for (const ep of endpoints) {
      lines.push(ep);
    }
    lines.push(`}`);
    lines.push(``);
  }

  const schemas = ((spec.components as Record<string, unknown>)?.schemas ?? {}) as Record<string, unknown>;
  let dataCount = 0;
  for (const [schemaName, schemaDef] of Object.entries(schemas)) {
    const schema = schemaDef as Record<string, unknown>;
    if (schema.type !== 'object' && !schema.properties) continue;
    const properties = (schema.properties ?? {}) as Record<string, unknown>;
    const fields = Object.entries(properties)
      .map(([key, val]) => `  ${key}: ${mapSchemaFieldType(val as Record<string, unknown>)}`);
    if (fields.length === 0) continue;
    lines.push(`data ${toPascalCase(schemaName)} {`);
    for (const f of fields) lines.push(f);
    lines.push(`}`);
    lines.push(``);
    dataCount++;
  }

  return {
    ag: lines.join('\n'),
    contracts: groups.size,
    endpoints: endpointCount,
    dataTypes: dataCount,
  };
}
