// Converts Terraform HCL resource blocks to aglang node declarations.
// Uses regex parsing — handles only top-level resource blocks; skips modules.
// Supported providers: AWS, Google Cloud, Azure.

export interface TerraformImportResult {
  ag: string;
  nodes: number;
  skipped: number;
}

const TF_TYPE_MAP: Record<string, string> = {
  aws_db_instance: 'postgres',
  aws_rds_cluster: 'postgres',
  aws_elasticache_cluster: 'redis',
  aws_elasticache_replication_group: 'redis',
  aws_s3_bucket: 'object_store',
  aws_sqs_queue: 'queue',
  aws_sns_topic: 'event_stream',
  aws_msk_cluster: 'message_queue',
  aws_alb: 'load_balancer',
  aws_lb: 'load_balancer',
  aws_api_gateway_rest_api: 'api_gateway',
  aws_lambda_function: 'serverless_fn',
  aws_dynamodb_table: 'dynamodb',
  aws_opensearch_domain: 'elasticsearch',
  aws_elasticsearch_domain: 'elasticsearch',
  aws_docdb_cluster: 'mongodb',
  aws_ecr_repository: 'container_registry',
  aws_ecs_cluster: 'container_cluster',
  aws_eks_cluster: 'container_cluster',
  aws_cognito_user_pool: 'auth_provider',
  aws_cloudfront_distribution: 'cdn',
  google_sql_database_instance: 'postgres',
  google_redis_instance: 'redis',
  google_storage_bucket: 'object_store',
  google_pubsub_topic: 'event_stream',
  google_pubsub_subscription: 'queue',
  google_container_cluster: 'container_cluster',
  google_cloud_run_service: 'serverless_fn',
  google_bigquery_dataset: 'analytics_db',
  google_firestore_database: 'mongodb',
  azurerm_sql_server: 'mssql',
  azurerm_mssql_server: 'mssql',
  azurerm_postgresql_server: 'postgres',
  azurerm_postgresql_flexible_server: 'postgres',
  azurerm_redis_cache: 'redis',
  azurerm_storage_account: 'object_store',
  azurerm_servicebus_namespace: 'message_queue',
  azurerm_eventhub_namespace: 'event_stream',
  azurerm_container_registry: 'container_registry',
  azurerm_kubernetes_cluster: 'container_cluster',
  azurerm_function_app: 'serverless_fn',
  azurerm_cosmosdb_account: 'mongodb',
  azurerm_api_management: 'api_gateway',
  azurerm_cdn_profile: 'cdn',
};

function toPascalCase(s: string): string {
  return s.replace(/[-_]+(.)/g, (_: string, c: string) => c.toUpperCase())
          .replace(/^(.)/, (_: string, c: string) => c.toUpperCase());
}

const RESOURCE_RE = /resource\s+"([^"]+)"\s+"([^"]+)"\s*\{/g;

export function importTerraform(hcl: string): TerraformImportResult {
  const lines: string[] = [
    `// Generated by aglc import-tf`,
    `// Source: Terraform HCL`,
    `// Note: Only top-level resource blocks are imported; modules are skipped.`,
    ``,
  ];

  let nodeCount = 0;
  let skippedCount = 0;
  let m: RegExpExecArray | null;

  while ((m = RESOURCE_RE.exec(hcl)) !== null) {
    const tfType = m[1]!;
    const tfName = m[2]!;

    const nodeType = TF_TYPE_MAP[tfType];
    if (!nodeType) {
      skippedCount++;
      continue;
    }

    const nodeName = toPascalCase(tfName);
    lines.push(`node ${nodeName} : ${nodeType} {`);
    lines.push(`  // terraform: ${tfType}.${tfName}`);
    lines.push(`}`);
    lines.push(``);
    nodeCount++;
  }

  if (nodeCount === 0 && skippedCount === 0) {
    lines.push(`// No recognized resource blocks found.`);
  }

  return {
    ag: lines.join('\n'),
    nodes: nodeCount,
    skipped: skippedCount,
  };
}
