#!/usr/bin/env node
// aglc — Architecture Ground Language Compiler CLI

import { readFileSync, writeFileSync, existsSync, mkdirSync, chmodSync } from 'fs';
import { resolve, dirname, basename } from 'path';
import { check } from './checker.ts';
import { emitArtifact, writeArtifact, loadArtifact } from './emitters/artifact.ts';
import { emitAgentsMarkdown } from './emitters/agents.ts';
import { emitSkillManifest, writeSkillManifest } from './emitters/skill.ts';
import { loadAndMerge, ImportError } from './importer.ts';
import { parseDiff } from './runtime/diff-parser.ts';
import { generateDeltaAssertions } from './runtime/delta-assert.ts';
import { runGate } from './runtime/gate.ts';
import { runContractGate } from './runtime/contract-gate.ts';
import { formatVerdict, formatVerdictJson } from './runtime/diagnostic.ts';
import type { ArchitectureArtifact } from './emitters/artifact.ts';
import { generateSpec } from './generate.ts';

const args = process.argv.slice(2);
const command = args[0];
const jsonMode = args.includes('--json');

// In JSON mode, progress logs go to stderr so stdout stays machine-parseable
const log = jsonMode
  ? (...a: unknown[]) => process.stderr.write(a.join(' ') + '\n')
  : console.log.bind(console);
const logErr = console.error.bind(console);

function usage() {
  console.log(`
aglc — Architecture Ground Language Compiler

Commands:
  aglc compile <file.ag>                              Compile .ag spec → architecture.o
  aglc generate [projectRoot] [--out <file.ag>]       Scan codebase → auto-generate starter .ag spec
  aglc emit-context --arch <arch.o> [--out <path>]   Emit AGENTS.md for AI agents
  aglc emit-skill   --arch <arch.o> [--out <path>]   Emit skill.json manifest for AI agents
  aglc install [--project <dir>] [--arch <arch.o>]   Install pre-commit git hook
  aglc check --arch <arch.o> --project <dir> [--json] Check staged git diff vs architecture
  aglc check-file --arch <arch.o> --file <f> [--json] [--dump-smt]  Analyze a specific file
  aglc import-openapi <swagger.json> [--out <file.ag>]    Import OpenAPI 3.x spec → .ag contracts
  aglc import-tf <main.tf> [--out <file.ag>]             Import Terraform → .ag node declarations

Flags:
  --json      Output machine-readable JSON to stdout; progress logs go to stderr
  --dump-smt  Write the full SMT-LIB script fed to Z3 → examples/debug.smt2
`);
  process.exit(1);
}

// ─────────────────────────────────────────────────────────────
// COMPILE
// ─────────────────────────────────────────────────────────────
async function compile(agPath: string) {
  const absPath = resolve(agPath);
  if (!existsSync(absPath)) {
    logErr(`Error: file not found: ${absPath}`);
    process.exit(1);
  }

  log(`[aglc] Resolving imports for ${basename(absPath)}...`);
  let ast;
  try {
    ast = loadAndMerge(absPath);
  } catch (e) {
    if (e instanceof ImportError) {
      logErr(`\n${e.message}`);
    } else {
      logErr(`\nParse error: ${(e as Error).message}`);
    }
    process.exit(1);
  }

  log(`[aglc] Type checking...`);
  const errors = check(ast);
  if (errors.length > 0) {
    logErr('\nType check errors:');
    for (const e of errors) {
      logErr(`  ✗ ${e.message}`);
    }
    process.exit(1);
  }

  log(`[aglc] Translating to SMT-LIB...`);
  const artifact = emitArtifact(ast, absPath);

  const outPath = resolve(dirname(absPath), 'architecture.o');
  writeArtifact(artifact, outPath);

  log(`\n✓ Compiled successfully → ${outPath}`);
  log(`  Components: ${Object.keys(artifact.mappings).length}`);
  log(`  Invariants: ${artifact.invariants.length}`);
  log(`  State machines: ${artifact.stateMachines.length}`);
  log(`  Permissions: ${artifact.permissions.length}`);
  log(`  Contracts: ${(artifact.contracts ?? []).length}`);
  log(`  SMT-LIB constraints: ${artifact.constraints.filter(s => s.startsWith('(')).length}`);
}

// ─────────────────────────────────────────────────────────────
// INSTALL (git pre-commit hook)
// ─────────────────────────────────────────────────────────────
function installHook(projectRoot: string, archPath: string) {
  const absProject = resolve(projectRoot);
  const hooksDir = resolve(absProject, '.git', 'hooks');

  if (!existsSync(resolve(absProject, '.git'))) {
    console.error(`Error: no .git directory found in ${absProject}`);
    process.exit(1);
  }

  mkdirSync(hooksDir, { recursive: true });
  const hookPath = resolve(hooksDir, 'pre-commit');
  const absArch = resolve(archPath);

  // Shell-safe: use single-quoted POSIX strings, no variable interpolation in values.
  // Use `npx aglc` — consumers have aglc as a listed dependency; npx will find the bin.
  // Paths are validated above (resolve()) and written as single-quoted literals so no
  // shell metacharacters ($, `, (, ), etc.) can be injected from path values.
  const safeSingleQuote = (s: string) => `'${s.replace(/'/g, `'\\''`)}'`;
  const hookScript = `#!/bin/sh
# aglang pre-commit hook — auto-generated by aglc install
# Checks staged files against architectural invariants before committing.
# To bypass (emergency only): git commit --no-verify

ARCH=${safeSingleQuote(absArch)}
PROJECT=${safeSingleQuote(absProject)}

if [ ! -f "$ARCH" ]; then
  echo "[aglc] Warning: architecture.o not found at $ARCH, skipping check."
  exit 0
fi

npx --no aglc check --arch "$ARCH" --project "$PROJECT"
if [ $? -ne 0 ]; then
  exit 1
fi
exit 0
`;

  writeFileSync(hookPath, hookScript, { encoding: 'utf8' });
  try {
    chmodSync(hookPath, 0o755);
  } catch {
    // chmod may not work on Windows — that's fine, WSL/Git will handle it
  }

  console.log(`✓ Installed pre-commit hook → ${hookPath}`);
  console.log(`  Architecture artifact: ${absArch}`);
  console.log(`  Project root:          ${absProject}`);
  console.log('');
  console.log('  On every git commit, aglc will check staged files against your architecture.');
  console.log('  To bypass (emergency only): git commit --no-verify');
}

// ─────────────────────────────────────────────────────────────
// EMIT-CONTEXT (AGENTS.md)
// ─────────────────────────────────────────────────────────────
function emitContext(archPath: string, outPath: string) {
  if (!existsSync(archPath)) {
    logErr(`Error: architecture.o not found: ${archPath}`);
    process.exit(1);
  }

  const artifact: ArchitectureArtifact = loadArtifact(readFileSync(archPath, 'utf8'));
  const md = emitAgentsMarkdown(artifact);
  writeFileSync(outPath, md, 'utf8');
  log(`✓ Emitted context → ${outPath}`);
  log(`  Nodes: ${(artifact.nodes ?? []).length}, Components: ${Object.keys(artifact.mappings).length}`);
  log(`  Invariants: ${artifact.invariants.length}, State machines: ${(artifact.stateMachines ?? []).length}, Permissions: ${(artifact.permissions ?? []).length}`);
  log(`  Enums: ${(artifact.enums ?? []).length}, Data types: ${(artifact.dataTypes ?? []).length}`);
}

// ─────────────────────────────────────────────────────────────
// EMIT-SKILL (skill.json)
// ─────────────────────────────────────────────────────────────
function emitSkill(archPath: string, outPath: string) {
  if (!existsSync(archPath)) {
    logErr(`Error: architecture.o not found: ${archPath}`);
    process.exit(1);
  }

  const artifact: ArchitectureArtifact = loadArtifact(readFileSync(archPath, 'utf8'));
  const manifest = emitSkillManifest(artifact, archPath);
  writeSkillManifest(manifest, outPath);
  log(`✓ Emitted skill manifest → ${outPath}`);
  log(`  Skill: ${manifest.skill} v${manifest.version}`);
  log(`  Use 'check_file' command in your agent to validate files before committing.`);
}

// ─────────────────────────────────────────────────────────────
// CHECK (git diff mode)
// ─────────────────────────────────────────────────────────────
async function checkDiff(archPath: string, projectRoot: string) {
  if (!existsSync(archPath)) {
    logErr(`Error: architecture.o not found: ${archPath}`);
    process.exit(1);
  }

  const artifact: ArchitectureArtifact = loadArtifact(readFileSync(archPath, 'utf8'));
  const absProject = resolve(projectRoot);

  log(`[aglc] Parsing git diff in ${absProject}...`);
  const changed = parseDiff(absProject, artifact);

  if (changed.length === 0) {
    if (jsonMode) {
      process.stdout.write(JSON.stringify({ schema_version: 2, passed: true, violations: [], contract_violations: [], warnings: [], contract_warnings: [], timestamp: new Date().toISOString(), artifact: archPath, agent_context: 'No staged changes in tracked components. Commit allowed.' }, null, 2) + '\n');
    } else {
      log(`[aglc] No staged changes in tracked components. Commit allowed.`);
    }
    process.exit(0);
  }

  log(`[aglc] Changed components: ${changed.map(c => c.componentName).join(', ')}`);
  log(`[aglc] Generating delta assertions...`);
  const delta = await generateDeltaAssertions(changed, artifact);

  // Run contract gate for all changed files (with completeness check since we have projectRoot)
  const allChangedFiles = changed.flatMap(c => c.files);
  const contractResult = await runContractGate(artifact, allChangedFiles, {
    projectRoot: absProject,
    checkCompleteness: true,
  });

  if (delta.blockingFacts.length === 0 && delta.warningFacts.length === 0 && contractResult.violations.length === 0) {
    const msg = 'No architectural violations detected. Commit allowed.';
    if (jsonMode) {
      process.stdout.write(JSON.stringify({
        schema_version: 2,
        passed: true,
        violations: [],
        contract_violations: [],
        warnings: [],
        contract_warnings: contractResult.warnings,
        timestamp: new Date().toISOString(),
        artifact: archPath,
        agent_context: msg,
      }, null, 2) + '\n');
    } else {
      if (contractResult.warnings.length > 0) {
        console.log(formatVerdict({
          passed: true, violations: [], warnings: [],
          contract_violations: [], contract_warnings: contractResult.warnings,
        }));
      } else {
        log(`[aglc] ${msg}`);
      }
    }
    process.exit(0);
  }

  log(`[aglc] Running Z3 solver...`);
  const verdict = await runGate(artifact, delta);

  verdict.contract_violations = contractResult.violations;
  verdict.contract_warnings = contractResult.warnings;
  verdict.passed = verdict.passed && contractResult.violations.length === 0;

  if (jsonMode) {
    process.stdout.write(formatVerdictJson(verdict, archPath) + '\n');
  } else {
    console.log(formatVerdict(verdict));
  }
  process.exit(verdict.passed ? 0 : 1);
}

// ─────────────────────────────────────────────────────────────
// CHECK-FILE (single file, for testing/debugging)
// ─────────────────────────────────────────────────────────────
async function checkFile(archPath: string, filePath: string) {
  if (!existsSync(archPath)) {
    logErr(`Error: architecture.o not found: ${archPath}`);
    process.exit(1);
  }
  if (!existsSync(filePath)) {
    logErr(`Error: file not found: ${filePath}`);
    process.exit(1);
  }

  const dumpSmt = args.includes('--dump-smt');
  const artifact: ArchitectureArtifact = loadArtifact(readFileSync(archPath, 'utf8'));
  const absFile = resolve(filePath);

  // Find which component this file belongs to
  const { default: micromatch } = await import('micromatch');
  let componentName: string | undefined;
  for (const [comp, glob] of Object.entries(artifact.mappings)) {
    if (micromatch.isMatch(absFile, `**/${glob}`) || micromatch.isMatch(absFile, glob)) {
      componentName = comp;
      break;
    }
  }

  if (!componentName) {
    // Fallback: match by directory keyword
    for (const [comp, glob] of Object.entries(artifact.mappings)) {
      const keyword = glob.split('/').find(p => p && !p.includes('*'));
      if (keyword && absFile.includes(keyword)) {
        componentName = comp;
        break;
      }
    }
  }

  if (!componentName) {
    if (jsonMode) {
      process.stdout.write(JSON.stringify({ schema_version: 2, passed: true, violations: [], contract_violations: [], warnings: [], contract_warnings: [], timestamp: new Date().toISOString(), artifact: archPath, agent_context: `File does not belong to any tracked component: ${absFile}` }, null, 2) + '\n');
    } else {
      log(`[aglc] File does not belong to any tracked component: ${absFile}`);
    }
    process.exit(0);
  }

  log(`[aglc] Analyzing ${absFile}`);
  log(`[aglc] Component: ${componentName}`);

  const delta = await generateDeltaAssertions(
    [{ componentName, files: [absFile] }],
    artifact,
  );

  // Run contract gate (if any contracts are declared)
  const contractResult = await runContractGate(artifact, [absFile]);
  if (contractResult.violations.length > 0 || contractResult.warnings.length > 0) {
    log(`[aglc] Contract check: ${contractResult.violations.length} violation(s), ${contractResult.warnings.length} warning(s)`);
  }

  if (delta.facts.length === 0 && contractResult.violations.length === 0) {
    if (contractResult.warnings.length > 0) {
      // Pass but show warnings
    } else {
      if (jsonMode) {
        process.stdout.write(JSON.stringify({
          schema_version: 2,
          passed: true,
          violations: [],
          contract_violations: [],
          warnings: [],
          contract_warnings: [],
          timestamp: new Date().toISOString(),
          artifact: archPath,
          agent_context: 'No architectural flow patterns detected.',
        }, null, 2) + '\n');
      } else {
        log(`[aglc] No architectural flow patterns detected. ✓`);
      }
      process.exit(0);
    }
  }

  if (delta.facts.length > 0) {
    log(`[aglc] Detected flows:`);
    for (const f of delta.facts) {
      const tag = f.confidence === 'definite' ? '🔴' : f.confidence === 'probable' ? '🟡' : '⚪';
      log(`  ${tag} [${f.confidence}] ${f.from} → ${f.to}: ${f.evidence}`);
    }
  }

  // Dump full SMT-LIB script to file if requested
  if (dumpSmt) {
    const smtScript = [...artifact.constraints, '', ...delta.smtAssertions].join('\n');
    const smtPath = resolve(dirname(archPath), 'debug.smt2');
    writeFileSync(smtPath, smtScript, 'utf8');
    log(`[aglc] SMT-LIB script written → ${smtPath}`);
  }

  log(`[aglc] Running Z3 solver...`);
  const verdict = await runGate(artifact, delta);

  // Merge contract gate results into verdict
  verdict.contract_violations = contractResult.violations;
  verdict.contract_warnings = contractResult.warnings;
  verdict.passed = verdict.passed && contractResult.violations.length === 0;

  if (jsonMode) {
    process.stdout.write(formatVerdictJson(verdict, archPath) + '\n');
  } else {
    console.log(formatVerdict(verdict));
  }
  process.exit(verdict.passed ? 0 : 1);
}

// ─────────────────────────────────────────────────────────────
// IMPORT-OPENAPI
// ─────────────────────────────────────────────────────────────
async function importOpenApiCmd(specPath: string, outPath: string | undefined) {
  const { importOpenApi } = await import('./import-openapi.ts');
  const { readFileSync, writeFileSync } = await import('fs');
  if (!existsSync(specPath)) {
    logErr(`Error: file not found: ${specPath}`);
    process.exit(1);
  }
  const json = readFileSync(specPath, 'utf8');
  const result = importOpenApi(json);
  if (outPath) {
    writeFileSync(outPath, result.ag, 'utf8');
    log(`✓ Imported OpenAPI spec → ${outPath}`);
  } else {
    process.stdout.write(result.ag);
  }
  log(`  Contracts: ${result.contracts}, Endpoints: ${result.endpoints}, Data types: ${result.dataTypes}`);
}

// ─────────────────────────────────────────────────────────────
// IMPORT-TF
// ─────────────────────────────────────────────────────────────
async function importTfCmd(hclPath: string, outPath: string | undefined) {
  const { importTerraform } = await import('./import-tf.ts');
  const { readFileSync, writeFileSync } = await import('fs');
  if (!existsSync(hclPath)) {
    logErr(`Error: file not found: ${hclPath}`);
    process.exit(1);
  }
  const hcl = readFileSync(hclPath, 'utf8');
  const result = importTerraform(hcl);
  if (outPath) {
    writeFileSync(outPath, result.ag, 'utf8');
    log(`✓ Imported Terraform → ${outPath}`);
  } else {
    process.stdout.write(result.ag);
  }
  log(`  Nodes imported: ${result.nodes}, Resource types skipped (unmapped): ${result.skipped}`);
}

// ─────────────────────────────────────────────────────────────
// Main dispatch
// ─────────────────────────────────────────────────────────────
function getArg(flag: string): string | undefined {
  const idx = args.indexOf(flag);
  return idx >= 0 ? args[idx + 1] : undefined;
}

(async () => {
  if (command === 'compile') {
    const agFile = args[1];
    if (!agFile) usage();
    await compile(agFile!);

  } else if (command === 'install') {
    const projectRoot = getArg('--project') ?? '.';
    const archPath = getArg('--arch') ?? 'architecture.o';
    installHook(projectRoot, archPath);

  } else if (command === 'emit-context') {
    const archPath = getArg('--arch') ?? 'architecture.o';
    const outPath = getArg('--out') ?? 'AGENTS.md';
    emitContext(archPath, outPath);

  } else if (command === 'emit-skill') {
    const archPath = getArg('--arch') ?? 'architecture.o';
    const outPath = getArg('--out') ?? 'skill.json';
    emitSkill(archPath, outPath);

  } else if (command === 'check') {
    const archPath = getArg('--arch') ?? 'architecture.o';
    const projectRoot = getArg('--project') ?? '.';
    await checkDiff(archPath, projectRoot);

  } else if (command === 'check-file') {
    const archPath = getArg('--arch') ?? 'architecture.o';
    const filePath = getArg('--file');
    if (!filePath) usage();
    await checkFile(archPath, filePath!);

  } else if (command === 'import-openapi') {
    const specPath = args[1];
    if (!specPath) usage();
    const outPath = getArg('--out');
    await importOpenApiCmd(specPath!, outPath);

  } else if (command === 'import-tf') {
    const hclPath = args[1];
    if (!hclPath) usage();
    const outPath = getArg('--out');
    await importTfCmd(hclPath!, outPath);

  } else if (command === 'generate') {
    const projectRoot = resolve(args[1] ?? '.');
    const outPath = getArg('--out');
    const projectName = getArg('--name');
    const result = await generateSpec(projectRoot, { projectName });
    if (outPath) {
      const { writeFileSync } = await import('fs');
      writeFileSync(outPath, result.ag, 'utf8');
      log(`✓ Generated ${outPath}`);
    } else {
      process.stdout.write(result.ag + '\n');
    }
    log(`  Components: ${result.components} | Infrastructure nodes: ${result.infrastructureNodes} | Contracts: ${result.contracts}`);
    for (const w of result.warnings) log(`  ⚠ ${w}`);

  } else {
    usage();
  }
})();
